services:

  api-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    networks:
      - eureka-net

networks:
  eureka-net:
    external: true
