server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/v1/auth/$\{segment}

            - id: event-availability
              uri: forward:/events
              predicates:
                  - Path=/events/*/availability
              order: -10

            - id: event-service-events
              uri: lb://event-service
              predicates:
                - Path=/events,/events/**
              filters:
                - RewritePath=/events(?<segment>/.*)?, /api/v1/events$\{segment}

            - id: event-service-venues
              uri: lb://event-service
              predicates:
                - Path=/venues,/venues/**
              filters:
                - RewritePath=/venues(?<segment>/.*)?, /api/v1/venues$\{segment}

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments, /payments/**
              filters:
                - RewritePath=/payments(?<segment>/.*)?, /api/v1/payments$\{segment}

            - id: booking-service-bookings
              uri: lb://booking-service
              predicates:
                - Path=/bookings,/bookings/**
              filters:
                - RewritePath=/bookings(?<segment>/.*)?, /api/v1/bookings$\{segment}
            
            - id: booking-service-tickets
              uri: lb://booking-service
              predicates:
                - Path=/tickets,/tickets/**
              filters:
                - RewritePath=/tickets(?<segment>/.*)?, /api/v1/tickets$\{segment}

            - id: swagger-user-service
              uri: lb://user-service
              predicates:
                - Path=/swagger/user
              filters:
                - RewritePath=/swagger/user, /v3/api-docs

            - id: swagger-event-service
              uri: lb://event-service
              predicates:
                - Path=/swagger/event
              filters:
                - RewritePath=/swagger/event, /v3/api-docs

            - id: swagger-booking-service
              uri: lb://booking-service
              predicates:
                - Path=/swagger/booking
              filters:
                - RewritePath=/swagger/booking, /v3/api-docs

            - id: swagger-payment-service
              uri: lb://payment-service
              predicates:
                - Path=/swagger/payment
              filters:
                - RewritePath=/swagger/payment, /v3/api-docs


springdoc:
  swagger-ui:
#    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /swagger/user
      - name: Event Service
        url: /swagger/event
      - name: Booking Service
        url: /swagger/booking
      - name: Payment Service
        url: /swagger/payment
      - name: Gateway Aggregations
        url: /gateway-aggregated.json 
jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.oauth2.jwt: TRACE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

