package com.bulka.bookingservice.exception;

public enum ApiErrorCode {
    VALIDATION_FAILED,
    MALFORMED_JSON,
    MISSING_REQUEST_HEADER,
    MISSING_IDEMPOTENCY_KEY,
    INVALID_UUID,
    INVALID_ENUM_VALUE,
    INVALID_DATE_FORMAT,
    INVALID_ARGUMENT,
    INVALID_STATE,

    UNAUTHORIZED,
    FORBIDDEN,

    BOOKING_NOT_FOUND,
    RESERVATION_NOT_FOUND,
    SEAT_VALIDATION_FAILED,
    SEATS_ALREADY_RESERVED,
    EVENT_SEAT_MISMATCH,

    INTERNAL_SERVER_ERROR
}
