server:
  port: 8083
  tomcat:
    accept-count: 10
    max-connections: 20
    threads:
      max: 10
      min-spare: 2

spring:
  application:
    name: booking-service

  datasource:
    url: ${BOOKING_DATASOURCE_URL}
    username: ${BOOKING_DB_USER}
    password: ${BOOKING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      init-commands:
        notify-keyspace-events: "Ex"

      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: com.bulka.bookingservice.kafka.dto.PaymentSucceededEvent
        spring.json.use.type.headers: false
jwt:
  public-key-path: classpath:keys/public_key.pem

redis:
  ttl-minute: 10


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
