package com.bulka.eventservice.exception;

public enum ApiErrorCode {

    VALIDATION_FAILED,
    MALFORMED_JSON,
    MISSING_REQUEST_HEADER,
    MISSING_IDEMPOTENCY_KEY,
    INVALID_UUID,
    INVALID_ENUM_VALUE,
    INVALID_DATE_FORMAT,
    INVALID_ARGUMENT,
    INVALID_STATE,

    RESOURCE_NOT_FOUND,
    VENUE_NOT_FOUND,
    SECTION_NOT_FOUND,
    SEAT_NOT_FOUND,
    EVENT_NOT_FOUND,
    EVENT_SEAT_NOT_FOUND,

    DUPLICATE_SEAT,
    DUPLICATE_SECTION,
    INVALID_EVENT_STATE,
    SEATS_NOT_AVAILABLE,

    EVENT_SEAT_DATA_INTEGRITY,
    INTERNAL_SERVER_ERROR,

    UNAUTHORIZED,
    FORBIDDEN
}