server:
  port: 8761
  tomcat:
    accept-count: 10
    max-connections: 20
    threads:
      max: 10
      min-spare: 2

spring:
  application:
    name: discovery-service

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
