package com.bulka.paymentservice.dto;

public enum ApiErrorCode {
    VALIDATION_FAILED,
    MALFORMED_JSON,
    MISSING_REQUEST_HEADER,
    MISSING_IDEMPOTENCY_KEY,
    INVALID_UUID,
    INVALID_ARGUMENT,

    UNAUTHORIZED,
    FORBIDDEN,

    PAYMENT_NOT_FOUND,
    PAYMENT_CREATION_FAILED,
    SUCCESS_PAYMENT_ALREADY_EXISTS,

    INTERNAL_SERVER_ERROR
}
