services:

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8084:8084"
    networks:
      - default
      - eureka-net
      - kafka-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19092,kafka-3:19092

    depends_on:
      - payment-postgres-db


  payment-postgres-db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"

networks:
  eureka-net:
    external: true
  kafka-net:
    external: true