services:

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8083:8083"
    networks:
      - default
      - eureka-net
    depends_on:
      - booking-postgres-db
      - booking-redis


  booking-postgres-db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  booking-redis:
    image: redis:8
#    ports:
#      - "6379:6379"

networks:
  eureka-net:
    external: true